wandb_version: 1

accum_iter:
  desc: null
  value: 1
model:
  desc: null
  value: SegFormer3D
in_channels:
  desc: null
  value: 1
lr:
  desc: null
  value: null
blr:
  desc: null
  value: 0.001
min_lr:
  desc: null
  value: 0
dist_on_itp:
  desc: null
  value: false
warmup_epochs:
  desc: null
  value: 20
device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 42
layer_decay:
  desc: null
  value: 0.75
clip_grad:
  desc: null
  value: null
num_workers:
  desc: null
  value: 8
pin_mem:
  desc: null
  value: true
resume:
  desc: null
  value: ''
world_size:
  desc: null
  value: 1
embed_dim:
  desc: null
  value: 1
local_rank:
  desc: null
  value: -1
dist_url:
  desc: null
  value: env://
nb_classes:
  desc: null
  value: 2
data_dir:
  desc: null
  value: /root/MSLesSeg24/data
datalist:
  desc: null
  value: null
modalities:
  desc: null
  value: T1,T2,FLAIR,T1ce
preprocess:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722428944
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.13
      5: 0.17.5
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
